apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: ${RCT_NAME}
spec:
  spec:
    devices:
      requests:
      - name: ${REQ_NAME}
        exactly:
          deviceClassName: ${REQ_DEVICE}.nvidia.com
          selectors:
          - cel:
              expression: |
                device.capacity['gpu.nvidia.com'].memory.isGreaterThan(quantity("${MEM_GPU_REQUIRED_GIB}Gi"))
                &&
                (has(device.attributes['gpu.nvidia.com'].profile) ?
                  device.attributes['gpu.nvidia.com'].profile != '1g.47gb' : true)
                &&
                (has(device.attributes['gpu.nvidia.com'].profile) ?
                  device.attributes['gpu.nvidia.com'].profile != '3g.95gb' : true)
