apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: ${RCT_NAME}
spec:
  spec:
    devices:
      requests:
      - name: ${REQ_NAME}
        exactly:
          deviceClassName: gpu.nvidia.com
